version: 2
updates:
  - package-ecosystem: elm
    directory: /
    schedule:
      interval: weekly
    assignees:
      - "cm-kazup0n"
    reviewers:
     - "cm-kazup0n"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees:
      - "cm-kazup0n"
    reviewers:
     - "cm-kazup0n"